version: '2'

services: 

  limesurvey:
    image: acspri/limesurvey:5.2.0
    build: .
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_PASSWORD: e/xa|m|ple
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: password
      LIMESURVEY_ADMIN_NAME: Lime Administrator
      LIMESURVEY_ADMIN_EMAIL: lime@lime.lime
    volumes:
      - ./plugins:/var/www/html/plugins
      - ./upload:/var/www/html/upload
      - ./config:/var/www/html/application/config

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: e/xa|m|ple

